# The URL the site will be built for
base_url = "https://beta.regeneration.org.au"
#base_url = "http://192.168.1.20:1111/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

minify_html = true

# For overriding the default output directory `public`, set it to another value (e.g.: "docs")
output_dir = "dist"

[markdown]
highlight_code = false
external_links_target_blank = true

[extra]

[[extra.nav_menu]]
title = "About"

    [[extra.nav_menu.menu]]
    path = "about/leaders.md"
    icon = "leaders"
    desc = "Pastors and Ministry Leaders"

    [[extra.nav_menu.menu]]
    path = "about/values_and_beliefs.md"
    icon = "bible"
    desc = "Our purpose and mission"

[[extra.nav_menu]]
title = "For Our Church"

    [[extra.nav_menu.menu]]
    path = "church/announcements.md"
    icon = "trumpet"
    desc = "What's Happening"

    [[extra.nav_menu.menu]]
    path = "church/mcs.md"
    icon = "group"
    desc = "Find a Small Group"

    [[extra.nav_menu.menu]]
    path = "church/childrens_ministry.md"
    icon = "baby"
    desc = "Faith like a Mustard Seed"

    [[extra.nav_menu.menu]]
    path = "connect/_index.md"
    icon = "handshake"
    desc = "Connect with Us"
    is_section = true
