# The URL the site will be built for
base_url = "https://regenchurch.github.io/website/"
#base_url = "http://192.168.1.20:1111/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

minify_html = true

# For overriding the default output directory `public`, set it to another value (e.g.: "docs")
output_dir = "dist"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false
external_links_target_blank = true

[extra]
# Put all your custom variables here
