import os
import hashlib
import requests

from constants import DB_SHA, OUTPUT_DIR
from pocketbase import PocketBase


def should_update(client: PocketBase) -> bool:
    local_path = os.path.join(OUTPUT_DIR, DB_SHA)

    response = requests.get(f"{client.base_url}/{DB_SHA}")
    response.raise_for_status()
    new_hash = hashlib.sha256(response.content).hexdigest()

    if os.path.exists(local_path):
        with open(local_path, "rb") as f:
            current_hash = hashlib.sha256(f.read()).hexdigest()

        if current_hash == new_hash:
            return False

    with open(local_path, "wb") as f:
        # The hash generated by python differs from the sha256sum implementation.
        f.write(response.content)

    return True
