name: Build and Deploy

on: 
  repository_dispatch:
    types: [pocketbase]

jobs:
  build:
    name: Build Website
    runs-on: self-hosted
    # env:
    #   CACHE_DIR: /runner/data/cache/

    steps:
    - name: Checkout main
      uses: actions/checkout@v6
    
    # Note: Don't know why this caching doesn't work.
    # - name: Restore local image cache
    #   run: |
    #     if [[ -d "$CACHE_DIR/processed_images" ]]; then
    #       cp -r "$CACHE_DIR/processed_images" "./static"
    #       echo "Copied $(ls './static/processed_images' | wc -l) processed image files"
    #     fi

    - name: Download zola
      uses: taiki-e/install-action@v2
      with:
        tool: zola@0.21.0

    - name: Setup bun
      uses: oven-sh/setup-bun@v2

    - name: Build with bun and zola
      env:
        GPG_PASSPHRASE: ${{ secrets.REGEN_PASSPHRASE }}
      run: |
        bun install
        bun gen-pocketbase.js $GPG_PASSPHRASE
        bun gen-sprites.js
        bun run prod

    # - name: Save local image cache
    #   run: |
    #     ls -la './static/processed_images' | grep front
    #     if [ -d "$CACHE_DIR" ]; then
    #       rm -r "$CACHE_DIR"
    #     fi
    #     mkdir -p "$CACHE_DIR"
    #     cp -r "./static/processed_images" "$CACHE_DIR"

    - name: Deploy
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy ./dist --project-name=website-stable
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
