name: Build and Deploy

on: 
  repository_dispatch:
    types: [pocketbase]

jobs:
  build:
    name: Build Website
    runs-on: self-hosted
    env:
      IMG_CACHE: /runner/data/cache/processed_images

    steps:
    - name: Checkout main
      uses: actions/checkout@v4

    
    - name: Restore local image cache
      run: |
        if [ -d "$IMG_CACHE" ]; then
          cp -r "$IMG_CACHE" ./static/processed_images
        fi

    - name: Download zola
      uses: taiki-e/install-action@v2
      with:
        tool: zola@0.20.0

    - name: Setup bun
      uses: oven-sh/setup-bun@v2

    - name: Build with bun and zola
      env:
        GPG_PASSPHRASE: ${{ secrets.REGEN_PASSPHRASE }}
      run: |
        bun install
        bun pocketbase.mjs $GPG_PASSPHRASE
        bun gen-sprites.mjs
        bun run prod

    - name: Save local image cache
      run: |
        if [ -d "$IMG_CACHE" ]; then
          rm -r "$IMG_CACHE"
        fi
        mkdir -p "$IMG_CACHE"
        cp -r ./static/processed_images/* "$IMG_CACHE/"

    - name: Deploy
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy ./dist --project-name=regen-website
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
