name: Build and Deploy Website

on: 
 push:
  branches:
   - stable

jobs:
  build:
    name: Build Website

    runs-on: self-hosted
    steps:
    - name: Checkout main
      uses: actions/checkout@v4

    - name: Download zola
      uses: taiki-e/install-action@v2
      with:
        tool: zola@0.20.0

    - name: Restore cached assets (images and binaries)
      id: cache-assets-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          pb/
        key: assets-${{ steps.assets-hash.outputs.hash }}
        restore-keys: |
          assets-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install python dependencies

    - name: Grab assets from Pocketbase
      env:
        GPG_PASSPHRASE: ${{ secrets.REGEN_PASSPHRASE }}
      run: 
      run: |
        pushd glue
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt 
        python main.py $GPG_PASSPHRASE
        deactivate
        popd

    - name: Save assets
      id: cache-assets-save
      uses: actions/cache/save@v4
      with:
        path: |
          pb/
        key: assets-${{ steps.assets-hash.outputs.hash }}

    - name: Setup bun
      uses: oven-sh/setup-bun@v2

    - name: Build with bun and zola
      run: |
        bun install
        bun run prod

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
      with:
        path: dist/

  deploy:
    name: Deploy the artifact created
    needs: build

    permissions:
      pages: write
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: self-hosted
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4

    - name: Deploy to github pages
      id: deployment
      uses: actions/deploy-pages@v4
