name: Build and Deploy

on: 
  push: false
#  push:
#   branches:
#    - stable

jobs:
  build:
    # No caching is used because the CMS is run on the same machine as
    # the self-hosted runner.
    name: Build Website
    runs-on: self-hosted

    steps:
    - name: Checkout main
      uses: actions/checkout@v4

    - name: Download zola
      uses: taiki-e/install-action@v2
      with:
        tool: zola@0.20.0

    - name: Setup bun
      uses: oven-sh/setup-bun@v2

    - name: Build with bun and zola
      env:
        GPG_PASSPHRASE: ${{ secrets.REGEN_PASSPHRASE }}
      run: |
        bun install
        bun pocketbase.mjs $GPG_PASSPHRASE
        bun run prod

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/

  deploy:
    name: Deploy the artifact created
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4

    - name: Deploy to github pages
      id: deployment
      uses: actions/deploy-pages@v4
